### ISSUE TITLE
5.2 As any user I want to view a drop down of major cities So I can choose a city to receive its weather info

### ISSUE THREAD

**Issue by NicoleJadeVivier** [myusernamesthisreal/DB_GUI_F22#22]
Given a user is on the weather page, when the user clicks on a drop down menu, a selection of cities come up so that I can choose which city to view weather for. Given that the user does not select a city from the list, when the user clicks the submit form button, they should be prompted with a message telling them to submit a city.

**Comment by myusernamesthisreal** [comment]
Using categories for this
