### ISSUE TITLE
6.4 As a registered user I want to be able to filter statistics by region so I can visualize trends in a larger area

### ISSUE THREAD

**Issue by BSkav** [myusernamesthisreal/DB_GUI_F22#28]
Given the user is on the locations page, when the user selects a region of the United States, they will be presented with the posts that are in that region
Given that a user is done filtering, they can clear the filters

**Comment by myusernamesthisreal** [comment]
May not be possible to do within our time frame

**Comment by myusernamesthisreal** [comment]
Use categories for this feature :)
