### ISSUE TITLE
5.4 As any user I want to see weather-related posts close to my chosen city To see what is going on near me

### ISSUE THREAD

**Issue by NicoleJadeVivier** [myusernamesthisreal/DB_GUI_F22#34]
Given that a user has submitted the city dropdown form, under the main weather display, there should be a log of past weather related events for that city. Given that a user has submitted the city dropdown menu, when the user clicks on one of the past events, the main weather display should change.

**Comment by myusernamesthisreal** [comment]
Using the Categories functionality for this
