### ISSUE TITLE
7.5 As a registered user, I want to remove my like from a post so that I can remove content that I no longer want made public

### ISSUE THREAD

**Issue by AustinWerth27** [myusernamesthisreal/DB_GUI_F22#38]
Given that a user is logged in and that they are viewing a post that they have already liked, when they press the like button again, then the post is "unliked" and no longer shows that the user liked the post.
Given that a user is not logged in, when they view a post, then they should not be able to unlike a post because they are unable to like a post.

**Comment by myusernamesthisreal** [comment]
Completed frontend side in sprint 4
