### ISSUE TITLE
8.5 As a registered user I want to filter the amount of pins shown on the city's event page so that I can find my desired event more easily

### ISSUE THREAD

**Issue by BSkav** [myusernamesthisreal/DB_GUI_F22#45]
Given that a user is viewing the locations page, when they want to look at a specific type of event, then there should be a feature that allows the user to choose what they're looking for and only show those events on the locations page
Given that a user is viewing the locations page, when the user wants to remove the filter, then page will return to its original look

**Comment by myusernamesthisreal** [comment]
Categories by extension - backend part was done in sprint 3
